apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: react-nodejs-app
data:
  # Backend configuration
  FRONTEND_URL: "http://react-app-service:3000"
  PORT: "8000"
  FIREBASE_PROJECT_ID: "test-b656c"
  
  # Frontend configuration
  REACT_APP_BACKEND_URL: "http://nodejs-api-service:8000" 