apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
  namespace: react-nodejs-app
  labels:
    app: react-frontend
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
        version: v1
    spec:
      containers:
      - name: react-frontend
        image: your-registry.com/react-nodejs-app-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: REACT_APP_BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: REACT_APP_BACKEND_URL
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "200m"
        # Health checks removed - React dev server takes time to start 